Hotfix/unit test cleanup
KronoSKoderS/CalPack pull request #57
Opened 2017-11-27 01:40 UTC by xlyk

Updates that prevent DeprecationWarnings while running unit tests along with some general PEP8 cleanup.

2017-11-27 07:11 UTC, mertzjames approved these changes
Great find!

2017-11-27 07:13 UTC, KronoSKoderS commented on tests/ArrayField_Test.py
> +        # expected_vals = list(range(10))
commenting this out isn't necessary.  Go ahead and feel free to remove the line since it's not used at all in the test.

2017-11-27 07:14 UTC, KronoSKoderS commented on tests/BasicPackets_Test.py
> +        hat the values are properly parsed.
hat --> that

2017-11-27 07:15 UTC, KronoSKoderS commented on tests/BasicPackets_Test.py
> +        hat the values are properly parsed.
Also I personally set the char limit to 120 however the typical 100 pep8 is fine.

2017-11-27 07:18 UTC, mertzjames requested changes
I've left a few comments that should be addressed (they're super small).  Once you make those updates, I'll merge into dev.  Thanks for you contribution!

2017-11-27 16:37 UTC, KronoSKoderS commented
I merged the changes that I've done recently into your pull request.

2017-11-28 03:48 UTC, xlyk commented
Latest commit contains requested updates. 

Also, I noticed one of the new unit tests are failing. Here are the details

`kyle@mbp [18:33:13] [~/Projects/CalPack] [hotfix/unit-test-cleanup *]
-> % python -m unittest discover tests -p '*_Test.py'
F....................................
======================================================================
FAIL: test_advpkt_create_complex_packet (AdvancedPackets_Test.Test_AdvancedPacket)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kylehanks/Projects/CalPack/tests/AdvancedPackets_Test.py", line 133, in test_advpkt_create_complex_packet
    self.assertEqual(b_str, c_b_str)
AssertionError: '\x03\x00\x00\x00\x00\x00\x00\x00\xc3\xf5H@\x00\x00\x00\x00\x1f\x85\xebQ' != '\x03\x00\x00\x00\xc3\xf5H@\x1f\x85\xebQ\xb8\x1e\t\xc0\x00\xb8\xf3\xfd\xd4x\xe9\xf6\x05@U\x9a\xf9\x7f\x00\x00\xff\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'

----------------------------------------------------------------------
Ran 37 tests in 0.005s

FAILED (failures=1)`

2017-11-28 05:23 UTC, KronoSKoderS commented
your changes did bring this.  This is an issue brought in from development branch.  It's a known issue that we'll have to address elsewhere.

2017-11-28 05:23 UTC, merged